OnlineShop/OnlineShop/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using OnlineShop.DBModels;

namespace OnlineShop.Controllers
{
    public class CustomerController : Controller
    {
        public static string EncMD5(string password)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            UTF8Encoding encoder = new UTF8Encoding();
            Byte[] originalBytes = encoder.GetBytes(password);
            Byte[] encodedBytes = md5.ComputeHash(originalBytes);
            password = BitConverter.ToString(encodedBytes).Replace("-", "");
            var result = password.ToLower();
            return result;
        }

        private DbModels db = new DbModels();
        // GET: Customer
        public ActionResult Index()
        {
            var customers = db.Customers.ToList();
            return View(customers.ToList());
        }

        // GET: Customer/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        public JsonResult CreateUser([Bind(Include = "Cid, Name, Username, Password, Phone, Address, Role")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                customer.Password = EncMD5(customer.Password);
                db.Customers.Add(customer);
                db.SaveChanges();
                return Json(new { Result = true });
            }

            return Json(new { Result = false });
        }

        // GET: Customer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customer/Edit/5
        [HttpPost]
        public JsonResult EditUser([Bind(Include = "Cid, Name, Username, Password, Phone, Address, Role")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                customer.Password = EncMD5(customer.Password);

                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { Result = true });
            }

            return Json(new { Result = false });
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            customer.Orders.Clear();
            db.Customers.Remove(customer);

            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

OnlineShop/OnlineShop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShop.DBModels;
using OnlineShop.Models;

namespace OnlineShop.Controllers
{
    public class OrderController : Controller
    {
        DbModels db = new DbModels();
        // GET: Order
        public ActionResult Index()
        {
            List<Product> products = db.Products.ToList();
            List<Order> orders = db.Orders.ToList();
            List<Customer> customers = db.Customers.ToList();
            List<OrderDetail> orderDetails = db.OrderDetails.ToList();

            var orderTable = (from ord in orders
                              join cus in customers on ord.CustomerID equals cus.Cid
                              join ordDetail in orderDetails on ord.OrderId equals ordDetail.OrderID
                              join product in products on ordDetail.ProductID equals product.Pid
                              select new OrderViewModel
                              {
                                  orders = ord,
                                  customers = cus,
                                  orDetail = ordDetail,
                                  products = product
                              });


            return View(orderTable);
        }

        // GET: Order/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Order/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Order/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Order/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Order/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Order/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

OnlineShop/OnlineShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShop.DBModels;
using System.Net;
using System.Data.Entity;
using System.IO;

namespace OnlineShop.Controllers
{
    public class ProductController : Controller
    {
        private DbModels db = new DbModels();
        // GET: Product
        public ActionResult Index()
        {
            var products = db.Products.ToList();
            return View(products.ToList());
        }

        // GET: Product/Details/5
        [Route("Product/ProductDetail-{id}")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product prod = db.Products.Find(id);
            if (prod == null)
            {
                return HttpNotFound();
            }
            return View(prod);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            ViewBag.SupplierID = new SelectList(db.Suppliers, "Sid", "SupplierName");

            ViewBag.Categories =
                new SelectList(
                    db.Categories.Select(c => new { Text = c.CategoryName, Value = c.CategoryID }).ToList()
                    , "Value"
                    , "Text");
            ProductViewModel productViewModel = new ProductViewModel();
            return View(productViewModel);
        }

        // POST: Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductViewModel productViewModel, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                var newProducts = new Product();

                //crate relatvie path
                string relativePath = "/ProductImages/" + DateTime.Now.Ticks.ToString() + "_" + ImageFile.FileName;
                // map the relative to physical path
                string physicalPath = Server.MapPath(relativePath);

                // check if the image folder exists
                string imageFolder = Path.GetDirectoryName(physicalPath);
                if (!Directory.Exists(imageFolder))
                {
                    Directory.CreateDirectory(imageFolder);
                }

                // save the image to physical path
                ImageFile.SaveAs(physicalPath);

                productViewModel.ImageURL = relativePath;

                productViewModel.UpdateProducts(newProducts);


                if (productViewModel.CategoryID != null)
                {
                    foreach (var cID in productViewModel.CategoryID)
                    {
                        var category = db.Categories.Find(cID);
                        if (category != null)
                        {
                            newProducts.Categories.Add(category);
                        }
                    }
                }

                db.Products.Add(newProducts);
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            return View();
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            ViewBag.Categories =
                new SelectList(
                    db.Categories.Select(c => new { Text = c.CategoryName, Value = c.CategoryID }).ToList()
                    , "Value"
                    , "Text");

            ProductViewModel productViewModel = new ProductViewModel(product);

            ViewBag.SupplierID = new SelectList(db.Suppliers, "Sid", "SupplierName", productViewModel.SupplierID);

            return View(productViewModel);
        }

        // POST: Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductViewModel productViewModel, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                var newProducts = db.Products.Find(productViewModel.Pid);
                if (newProducts == null)
                {
                    return HttpNotFound();
                }

                if (ImageFile != null)
                {

                    string relativePath = "/NewsImages/" + DateTime.Now.Ticks.ToString() + "_" + ImageFile.FileName;

                    string physicalPath = Server.MapPath(relativePath);


                    string imageFolder = Path.GetDirectoryName(physicalPath);
                    if (!Directory.Exists(imageFolder))
                    {
                        Directory.CreateDirectory(imageFolder);

                    }

                    ImageFile.SaveAs(physicalPath);
                    productViewModel.ImageURL = relativePath;


                }

                productViewModel.UpdateProducts(newProducts);

                newProducts.Categories.Clear();

                if (productViewModel.CategoryID != null)
                {
                    foreach (var cID in productViewModel.CategoryID)
                    {
                        var category = db.Categories.Find(cID);
                        if (category != null)
                        {
                            newProducts.Categories.Add(category);
                        }
                    }
                }

                db.Entry(newProducts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productViewModel);
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            product.Categories.Clear();
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

OnlineShop/OnlineShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

OnlineShop/OnlineShop/Views/Shared/_Sidebar.cshtml
@using OnlineShop.DBModels

@{ 
    DbModels db = new DbModels();
    ViewBag.Categories = db.Categories;
}


<!-- Sidebar -->
<ul class="sidebar navbar-nav">
    <li class="nav-item active">
        <a class="nav-link" href="/">
            <i class="fas fa-home"></i>
            <span>HomePage</span>
        </a>
    </li>

    @if (Session["AdminID"] != null)
    {
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Category")">
                <i class="far fa-list-alt"></i>
                <span>Category</span>
            </a>
        </li>

        <li class="nav-item">
            @if (ViewBag.Categories != null)
            {
                foreach (Category cate in (IEnumerable<Category>)ViewBag.Categories)
                {
                    <a class="nav-link" href="/categories/@cate.CategoryID/@cate.CategoryName">
                        <i></i>
                        <span>@cate.CategoryName</span>
                    </a>
                }
            }
        </li>

        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Product")">
                <i class="fa fa-briefcase"></i>
                <span>Product</span>
            </a>
        </li>

        

        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Supplier")">
                <i class="fas fa-copyright"></i>
                <span>Supplier</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Customer")">
                <i class="fa fa-user-circle"></i>
                <span>User</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index","Cart")">
                <i class="fas fa-shopping-cart"></i>
                <span>Cart</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index","Order")">
                <i class="fas fa-atlas"></i>
                <span>Order</span>
            </a>
        </li>
    }
    @if (Session["UserID"] != null)
    {
        <li class="nav-item">
            @if (ViewBag.Categories != null)
            {
                foreach (Category cate in (IEnumerable<Category>)ViewBag.Categories)
                {
                    <a class="nav-link" href="/categories/@cate.CategoryID/@cate.CategoryName">
                        <i></i>
                        <span>@cate.CategoryName</span>
                    </a>
                }
            }
        </li>

        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index","Cart")">
                <i class="fas fa-shopping-cart"></i>
                <span>Cart</span>
            </a>
        </li>
    }



</ul>

OnlineShop/OnlineShop/Views/Shared/_mainLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Online Shop</title>
    <!-- Custom fonts for this template-->
    <link href="~/Assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="~/Assets/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/Assets/css/sb-admin.css" rel="stylesheet">

    <script src="~/Scripts/jquery-3.4.1.js"></script>
    
    <script src="~/Scripts/jquery.validate.min.js"></script>
</head>
<body id="page-top">
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
        <a class="navbar-brand mr-1" href="@Url.Action("HomePage", "HomePage")">Online Shop</a>
        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>
        <!-- Navbar Search -->
        <!-- Navbar -->
        <ul class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">

            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle fa-fw"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" style="font-weight:500" href="@Url.Action("Login","Login")">Login</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" style="font-weight:500" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
                </div>

            </li>
        </ul>
    </nav>
    <div id="wrapper">
        @RenderPage("_Sidebar.cshtml")
        <div id="content-wrapper">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="@Url.Action("Logout","Login")">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <style>
        .footer {
            background: #212529;
            color: #d3d3d3;
            text-align: center;
            bottom: 0;
            position: fixed;
            width: 100%;
        }
    </style>


    <div class="footer">

        Copyright ©

        2019
        Online Shop. All rights reserved.


    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/Assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/Assets/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Page level plugin JavaScript-->
    <script src="~/Assets/vendor/chart.js/Chart.min.js"></script>
    <script src="~/Assets/vendor/datatables/jquery.dataTables.js"></script>
    <script src="~/Assets/vendor/datatables/dataTables.bootstrap4.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/Assets/js/sb-admin.min.js"></script>
    <!-- Demo scripts for this page-->
    <script src="~/Assets/js/demo/datatables-demo.js"></script>
    <script src="~/Assets/js/demo/chart-area-demo.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>